version: '3.2'
services:
  aybush_bot:
    container_name: AybushBot
    build: .
    image: skarakasoglu/aybush-bot:1.0.0
    restart: always
    environment:
      applicationMode: Release
      applicationName: "Aybush Bot"
      executablePath: bin
      executableName: AybushBot
      discordAccessToken: discord_access_token
      twitchClientId: twitch_client_id
      twitchClientSecret: twitch_client_secret
      twitchRefreshToken: twitch_refresh_token
      dbIpAddress: 1.2.3.4
      dbPort: 5432
      dbUsername: db_username
      dbPassword: db_password
      dbName: db_name
      webhookHubSecret: very_secret
      certFile: /path/to/ssl/cert/file
      keyFile: /path/to/ssl/key/file
      GIN_MODE: debug
      streamlabsAccessToken: access_token
      shopierUsername: username
      shopierKey: key
    ports:
    - "8090:443"
    - "8091:444"